#!/bin/bash

set -ex

FONT_URL=https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Go-Mono.zip
FILE=$(mktemp --suffix=.zip)
FONT_DIR=$HOME/.local/share/fonts

curl -o $FILE -L $FONT_URL
mkdir -p $FONT_DIR
unzip $FILE -d $FONT_DIR
fc-cache -f -v

