import = [
  "~/.config/alacritty/themes/themes/solarized_dark.toml",
  "~/.config/alacritty/local.toml"
]

[font]
size = 13

[font.bold]
family = "GoMono Nerd Font Mono"
style = "bold"

[font.italic]
family = "GoMono Nerd Font Mono"
style = "italic"

[font.normal]
family = "GoMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "Full"
opacity = 0.97

[window.dimensions]
columns = 160
lines = 80
