import = [
  "~/.config/alacritty/themes/themes/solarized_osaka.toml",
  # "~/.config/alacritty/themes/themes/solarized_light.toml",
  "~/.config/alacritty/local.toml",
]

[font.bold]
family = "GoMono Nerd Font Mono"
style = "bold"

[font.italic]
family = "GoMono Nerd Font Mono"
style = "italic"

[font.normal]
family = "GoMono Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9
padding = { x = 6, y = 6 }
